# Azure Pipelines configuration
# trigger:
#   - master

jobs:
  - job: gcc54_cxx11
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: which g++ && g++ --version
        displayName: 'Check GCC version'
      - template: .ci/azure-pipelines/steps-install-cmake.yml
      - template: .ci/azure-pipelines/steps-cmake.yml

  - job: gcc54_cxx14
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: which g++ && g++ --version
        displayName: 'Check GCC version'
      - template: .ci/azure-pipelines/steps-install-cmake.yml
      - template: .ci/azure-pipelines/steps-cmake.yml
        parameters:
          cxxstd: '14'

  - job: 'vs2017_cxx11'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: .ci/azure-pipelines/steps-install-cmake.yml
      - template: .ci/azure-pipelines/steps-cmake.yml
        parameters:
          cmake: 'C:\cmake\bin\cmake'
          ctest: 'C:\cmake\bin\ctest'

  - job: 'vs2017_cxx14'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: .ci/azure-pipelines/steps-install-cmake.yml
      - template: .ci/azure-pipelines/steps-cmake.yml
        parameters:
          cxxstd: '14'
          cmake: 'C:\cmake\bin\cmake'
          ctest: 'C:\cmake\bin\ctest'

  - job: 'vs2017_cxx17'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: .ci/azure-pipelines/steps-install-cmake.yml
      - template: .ci/azure-pipelines/steps-cmake.yml
        parameters:
          cxxstd: '14'
          cmake: 'C:\cmake\bin\cmake'
          ctest: 'C:\cmake\bin\ctest'

  - job: 'vs2017_cxxlatest'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: .ci/azure-pipelines/steps-install-cmake.yml
      - template: .ci/azure-pipelines/steps-cmake.yml
        parameters:
          cxxstd: '20'
          cmake: 'C:\cmake\bin\cmake'
          ctest: 'C:\cmake\bin\ctest'

  - job: 'xcode91_cxx11'
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - template: .ci/azure-pipelines/steps-install-cmake.yml
      - template: .ci/azure-pipelines/steps-cmake.yml

  - job: 'xcode91_cxx14'
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - template: .ci/azure-pipelines/steps-install-cmake.yml
      - template: .ci/azure-pipelines/steps-cmake.yml
        parameters:
          cxxstd: '14'

  - job: 'xcode91_cxx17'
    pool:
      vmImage: 'macOS-10.13'
    steps:
      - template: .ci/azure-pipelines/steps-install-cmake.yml
      - template: .ci/azure-pipelines/steps-cmake.yml
        parameters:
          cxxstd: '17'
